import { Language } from './types';

export const translations = {
  en: {
    title: "EXAMHALL",
    subtitle: "Expand your horizons with interactive assessments",
    navDashboard: "Dashboard",
    navLeaderboard: "Leaderboard",
    navAdmin: "Admin Console",
    navProfile: "My Profile",
    language: "Language",
    logout: "Log Out",
    login: "Log In",
    signup: "Sign Up",
    fullName: "Full Name",
    email: "Email Address",
    password: "Password",
    roleSelection: "Request Role / Testing Access",
    studentRole: "Student (View & Take Quizzes)",
    adminRole: "Admin (Create & Manage Quizzes)",
    alreadyHaveAccount: "Already have an account? Log In",
    dontHaveAccount: "Don't have an account yet? Sign Up",
    forgotPassLink: "Forgot Password?",
    resetPassTitle: "Reset Password",
    resetPassLabel: "Enter New Password",
    backToLogin: "Back to Login",
    sendReset: "Save New Password",
    testCredentialsHint: "For quick testing, use:",
    adminDefault: "Admin: admin@quiz.com | Password: admin123",
    studentDefault: "Student: student@quiz.com | Password: student123",
    devPermitLabel: "Developer Permit Code (Required for Admin roles)",
    devPermitPlaceholder: "Enter admin developer permit code",
    devPermitRequiredError: "Developer permit code is required for registering as Admin.",

    // Quiz search
    searchPlaceholder: "Search quizzes by name or subject...",
    allSubjects: "All Subjects",
    computerScience: "Computer Science",
    generalKnowledge: "General Knowledge",
    takeQuizBtn: "Take Assessment",
    questionsCount: "Questions",
    durationLabel: "Minutes",
    minutesText: "mins",

    // Quiz Interface
    timerRemaining: "Time Remaining",
    questionProgress: "Question",
    of: "of",
    previousBtn: "Previous",
    nextBtn: "Next",
    submitQuizBtn: "Finish & Submit Quiz",
    confirmSubmitTitle: "Are you sure you want to submit?",
    confirmSubmitDesc: "You have answered all questions. Your answers will be graded immediately.",
    cancelBtn: "Keep Reviewing",
    yesSubmitBtn: "Yes, Evaluate My Score",

    // Results Summary
    quizResultsTitle: "Quiz Evaluation Report",
    totalScoreLabel: "Result Score",
    passedStatus: "PASSED",
    failedStatus: "FAILED",
    correctAnswers: "Correct Answers",
    wrongAnswers: "Wrong Answers",
    percentageLabel: "Percentage Achieved",
    timeSpent: "Time Spent",
    detailedReview: "Detailed Answer Review",
    yourAnswer: "Your Answer",
    correctAnswer: "Correct Answer",
    explanationLabel: "Explanation",
    downloadPDF: "Download Result Sheet",
    emailResultBtn: "Email Score Sheet",
    emailSuccess: "Your scorecard has been successfully dispatched to your email address!",
    returnDashboard: "Return to Dashboard",

    // Admin Dashboard
    adminStatsTitle: "Platform-wide Health Analytics",
    totalUsers: "Total Users Enrolled",
    totalQuizzes: "Total Quizzes Created",
    totalAttempts: "Total Quiz Attempts",
    averagePlatformScore: "Average Grade Score",
    scoreDistribution: "Student Score Distribution",
    subjectDistribution: "Attempts by Subject Category",
    manageQuizzes: "Manage Quizzes",
    createQuizManual: "Create Quiz Manually",
    uploadQuestionsCSV: "Parse CSV / Import File",
    editQuiz: "Edit Quiz",
    publishQuiz: "Publish Quiz",
    unpublishQuiz: "Unpublish Quiz",
    deleteQuiz: "Delete Quiz",
    quizTitleLabel: "Quiz Title",
    subjectLabel: "Subject Category",
    durationInput: "Duration limit (minutes)",
    descriptionLabel: "Short Assessment Summary",
    addQuestionBtn: "Add Multiple Choice Question",
    deleteQuestion: "Remove",
    questionText: "Question Statement",
    optionsList: "Multiple Choice Options",
    correctAnswerLabel: "Indicate Core Correct Option",
    explanationHelper: "Detailed Explanation (Optional)",
    saveQuizBtn: "Save and Publish Quiz",
    saveDraftBtn: "Save as Draft",

    // CSV Bulk Upload
    bulkUploadTitle: "Fast CSV Questions Importer",
    csvPasteLabel: "Paste Question Records in CSV Format",
    csvPlaceholder: "Question text,Option A,Option B,Option C,Option D,Correct Option (A/B/C/D),Explanation text",
    validateCSVBtn: "Validate and Preview Importer",
    previewTitle: "CSV Preview Table",
    publishCSVTitle: "Publish Imported Quiz",
    importSuccessMsg: "CSV parsed successfully! Check preview below.",
    importPublishBtn: "Import and Generate Live Quiz",

    // Profile & Leaderboard
    leaderboardTitle: "Global Elite Standings",
    rank: "Rank",
    quizzesCompleted: "Assessments Completed",
    averageAccuracy: "Average Score Accuracy",
    noHistoryYet: "No attempt logs available yet.",
    userAttemptHistoryTitle: "Personal Performance History",
    quizName: "Quiz name",
    dateTaken: "Date",
    gradeScore: "Grade Score",
    statusText: "Status",
    switchRoleToast: "Your account role has been overridden!",
    
    // Re-participation Lockout & Approvals
    lockoutTitle: "Retake Lock Active",
    lockoutDesc: "To ensure fair testing, you can only attempt each exam once every 12 hours. You can request admin approval to participate again.",
    lockoutTimeRemaining: "Retake available in",
    requestRetakeBtn: "Request Admin Approval to Retake Now",
    requestPending: "Request Pending Approval by Admin ⏳",
    requestApproved: "Request Approved! You can retake the exam now 🔓",
    requestRejected: "Request Rejected. You can submit another request ❌",
    sendRequestSuccess: "Your re-participation request has been sent for admin review!",
    approvalsTab: "Retake Approvals",
    adminApprovalsTitle: "Student Retake Requests",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    studentLabel: "Student",
    requestedExam: "Requested Exam",
    requestDate: "Request Date",
    statusCol: "Status",
    actionsCol: "Actions",
    noPendingRequests: "No pending or resolved retake requests found.",

    // Dynamic Submenus
    subMenusTab: "Sub-Menus",
    manageSubMenusTitle: "Manage Class Sub-Menus (Classes 6 to 10)",
    addSubMenuBtn: "Add Sub-Menu",
    subMenuParentLabel: "Parent Class Category",
    subMenuTitleEn: "Sub-menu Title (English)",
    subMenuTitleBn: "Sub-menu Title (Bengali)",
    existingSubMenusTitle: "Existing Sub-Menus",
    deleteSubMenuTooltip: "Delete this sub-menu selection",
    noSubMenusFound: "No custom sub-menus defined. Defaults will be seeded.",
    linkedSubMenuLabel: "Associated Sub-Menu",
    selectSubMenuDefault: "Select Sub-Menu (Optional)",
    clearFilterBtn: "Clear Sub-Menu Filter",
    activeSubMenuLabel: "Active sub-menu filter:",
    confirmSignOutTitle: "Are you sure you want to sign out?",
    confirmSignOutDesc: "You will be logged out of your session. Any active exam draft state will be lost.",
    confirmClearFiltersTitle: "Are you sure you want to clear your active filters?",
    confirmClearFiltersDesc: "This will reset all current filters including selected class and sub-menus to show all available assessments.",
    confirmSubmitAnswersTitle: "Are you sure you want to submit your answers?",
    confirmSubmitAnswersDesc: "Your exam sheet will be turned in for grading. You cannot modify your answers once submitted.",
    
    // Offline capabilities
    offlineStatus: "Offline Mode",
    onlineStatus: "Online Mode",
    viewCachedQuizzes: "Viewing Cached Exams",
    cachedBadge: "Offline Ready",
    downloadForOffline: "Download Exam",
    savedOfflineDetail: "Saved Locally",
    offlineSyncPendingCount: "exams awaiting sync",
    syncOfflineAttemptsNow: "Sync Saved Exams",
    syncSuccess: "Pristine Sync Completed!",
    syncedLabel: "Synced",
    offlineAttemptSavedAlert: "Assessment completed offline. Your score has been saved locally and will auto-sync once internet is restored!",
    noInternetConnection: "No internet connection detected.",
    showingLocalCache: "Showing cached offline content.",

    // Guest Invite translations
    guestHeaderTitle: "Guest Student Access",
    guestHeaderDesc: "You have been invited to participate in this exam without registering a full account. Enter your name below to start.",
    guestInputName: "Enter Your Full Name to Start",
    guestInputNamePlaceholder: "e.g., Jane Doe",
    startAsGuestBtn: "Proceed and Start Exam ➔",
    orLoginRegister: "Back to Login / Register Page",
    inviteLinkBtn: "Copy Invite Link",
    inviteCopiedToast: "Direct invite link copied!"
  },
  bn: {
    title: "EXAMHALL",
    subtitle: "ইন্টারেক্টিভ টেস্ট ও মূল্যায়নের মাধ্যমে নতুন জ্ঞান লাভ করুন",
    navDashboard: "ড্যাশবোর্ড",
    navLeaderboard: "লিডারবোর্ড",
    navAdmin: "অ্যাডমিন প্যানেল",
    navProfile: "আমার প্রোফাইল",
    language: "ভাষা",
    logout: "লগ আউট",
    login: "লগ ইন",
    signup: "সাইন আপ",
    fullName: "পূর্ণ নাম",
    email: "ইমেইল ঠিকানা",
    password: "পাসওয়ার্ড",
    roleSelection: "ভুমিকা নির্বাচন (টেস্টিং অ্যাক্সেস)",
    studentRole: "শিক্ষার্থী (টেস্ট দিতে পারবেন)",
    adminRole: "অ্যাডমিন (কুইজ ও প্রশ্ন পরিচালনা)",
    alreadyHaveAccount: "আগে থেকেই অ্যাকাউন্ট আছে? লগ ইন করুন",
    dontHaveAccount: "অ্যাকাউন্ট নেই? সাইন আপ করুন",
    forgotPassLink: "পাসওয়ার্ড ভুলে গেছেন?",
    resetPassTitle: "পাসওয়ার্ড পরিবর্তন",
    resetPassLabel: "নতুন পাসওয়ার্ড লিখুন",
    backToLogin: "লগইনে ফিরে যান",
    sendReset: "নতুন পাসওয়ার্ড সংরক্ষণ করুন",
    testCredentialsHint: "সহজে পরীক্ষা করার জন্য ব্যবহার করুন:",
    adminDefault: "অ্যাডমিন: admin@quiz.com | পাসওয়ার্ড: admin123",
    studentDefault: "শিক্ষার্থী: student@quiz.com | পাসওয়ার্ড: student123",
    devPermitLabel: "ডেভেলপার পারমিট কোড (অ্যাডমিন রোলের জন্য আবশ্যিক)",
    devPermitPlaceholder: "অ্যাডমিন ডেভেলপার পারমিট কোড লিখুন",
    devPermitRequiredError: "অ্যাডমিন হিসেবে নিবন্ধনের জন্য ডেভেলপার পারমিট কোড আবশ্যক।",

    // Quiz search
    searchPlaceholder: "নাম বা বিষয় দিয়ে কুইজ খুঁজুন...",
    allSubjects: "সব বিষয়",
    computerScience: "কম্পিউটার সায়েন্স",
    generalKnowledge: "সাধারণ জ্ঞান",
    takeQuizBtn: "পরীক্ষায় অংশগ্রহণ করুন",
    questionsCount: "প্রশ্ন সংখ্যা",
    durationLabel: "সময়",
    minutesText: "মিনিট",

    // Quiz Interface
    timerRemaining: "অবশিষ্ট সময়",
    questionProgress: "প্রশ্ন",
    of: "এর",
    previousBtn: "পূর্ববর্তী",
    nextBtn: "পরবর্তী",
    submitQuizBtn: "কুইজ জমা দিন",
    confirmSubmitTitle: "আপনি কি নিশ্চিতভাবে জমা দিতে চান?",
    confirmSubmitDesc: "আপনি সব প্রশ্নের উত্তর দিয়েছেন। আপনার উত্তরগুলি অবিলম্বে মূল্যায়ন করা হবে।",
    cancelBtn: "আবার পর্যালোচনা করুন",
    yesSubmitBtn: "হ্যাঁ, মূল্যায়ন করুন",

    // Results Summary
    quizResultsTitle: "কুইজ মূল্যায়ন রিপোর্ট",
    totalScoreLabel: "অর্জিত স্কোর",
    passedStatus: "উত্তীর্ণ",
    failedStatus: "অনুত্তীর্ণ",
    correctAnswers: "সঠিক উত্তর",
    wrongAnswers: "ভুল উত্তর",
    percentageLabel: "শতকরা হার",
    timeSpent: "ব্যয়িত সময়",
    detailedReview: "বিস্তারিত উত্তর পর্যালোচনা",
    yourAnswer: "আপনার দেওয়া উত্তর",
    correctAnswer: "সঠিক উত্তর",
    explanationLabel: "ব্যাখ্যা",
    downloadPDF: "ফলাফল শিট ডাউনলোড করুন",
    emailResultBtn: "ফলাফল ইমেইল করুন",
    emailSuccess: "আপনার স্কোরকার্ডটি সফলভাবে আপনার ইমেইল ঠিকানায় পাঠানো হয়েছে!",
    returnDashboard: "ড্যাশবোর্ডে ফিরে যান",

    // Admin Dashboard
    adminStatsTitle: "প্ল্যাটফর্মের সার্বিক পরিসংখ্যান",
    totalUsers: "মোট নিবন্ধিত শিক্ষার্থী",
    totalQuizzes: "মোট তৈরি করা কুইজ",
    totalAttempts: "মোট কুইজ মূল্যায়ন",
    averagePlatformScore: "গড় অর্জিত স্কোর",
    scoreDistribution: "শিক্ষার্থীদের স্কোর ডিস্ট্রিবিউশন",
    subjectDistribution: "বিষয়ভিত্তিক পরীক্ষার সংখ্যা",
    manageQuizzes: "কুইজ ব্যবস্থাপনা",
    createQuizManual: "নতুন কুইজ তৈরি",
    uploadQuestionsCSV: "সিএসভি ফাইল ইমপোর্ট করুন",
    editQuiz: "কুইজ এডিট করুন",
    publishQuiz: "প্রকাশ করুন (Publish)",
    unpublishQuiz: "ড্রাফট করুন (Unpublish)",
    deleteQuiz: "কুইজ মুছে ফেলুন",
    quizTitleLabel: "কুইজ শিরোনাম",
    subjectLabel: "বিষয় বা ক্যাটাগরি",
    durationInput: "সময় সীমা (মিনিট)",
    descriptionLabel: "কুইজের ছোট বিবরণী",
    addQuestionBtn: "নতুন এমসিকিউ প্রশ্ন যোগ করুন",
    deleteQuestion: "মুছে ফেলুন",
    questionText: "প্রশ্ন বিবরণ",
    optionsList: "বহুনির্বাচনী অপশনসমূহ",
    correctAnswerLabel: "সঠিক উত্তর অপশন নির্বাচন করুন",
    explanationHelper: "বিস্তারিত ব্যাখ্যা (ঐচ্ছিক)",
    saveQuizBtn: "কুইজ সংরক্ষণ ও প্রকাশ করুন",
    saveDraftBtn: "ড্রাফট হিসেবে রাখুন",

    // CSV Bulk Upload
    bulkUploadTitle: "সহজ সিএসভি প্রশ্ন আমদানিকারক",
    csvPasteLabel: "সিএসভি ফরম্যাটে প্রশ্নের ডাটা পেস্ট করুন",
    csvPlaceholder: "প্রশ্ন বিবরণ,অপশন এ,অপশন বি,অপশন সি,অপশন ডি,সঠিক অপশন (A/B/C/D),ব্যাখ্যা বিবরণ",
    validateCSVBtn: "সিএসভি যাচাই ও প্রিভিউ করুন",
    previewTitle: "সিএসভি ডাটা প্রিভিউ",
    publishCSVTitle: "আমদানীকৃত কুইজ প্রকাশ করুন",
    importSuccessMsg: "সিএসভি ডেটা সফলভাবে পার্স করা হয়েছে! নিচের টেবিলে প্রিভিউ দেখুন।",
    importPublishBtn: "আমদানি এবং লাইভ কুইজ তৈরি করুন",

    // Profile & Leaderboard
    leaderboardTitle: "গ্লোবাল সেরা অর্জনকারীদের তালিকা",
    rank: "র‍্যাংক",
    quizzesCompleted: "সমাপ্ত মূল্যায়ন",
    averageAccuracy: "গড় নম্বর অ্যাকুরেসি",
    noHistoryYet: "এখনো কোনো পরীক্ষার ইতিহাস নেই।",
    userAttemptHistoryTitle: "ব্যক্তিগত ফলাফল ও ইতিহাস",
    quizName: "কুইজের নাম",
    dateTaken: "তারিখ",
    gradeScore: "অর্জিত স্কোর",
    statusText: "ফলাফল",
    switchRoleToast: "আপনার অ্যাকাউন্টের রোল বা ভুমিকা পরিবর্তন করা হয়েছে!",

    // Re-participation Lockout & Approvals
    lockoutTitle: "পুনরায় পরীক্ষা লকআউট সক্রিয়",
    lockoutDesc: "সুষ্ঠু মূল্যায়নের জন্য প্রতিটি পরীক্ষায় অংশগ্রহণ করার পর পুনরায় অংশগ্রহণের জন্য ১২ ঘণ্টার বিরতি বাধ্যতামূলক। আপনি এখনই পুনরায় অংশ নেওয়ার জন্য অ্যাডমিনের অনুমোদনের আবেদন করতে পারেন।",
    lockoutTimeRemaining: "লকআউট সক্রিয়। পুনরায় পরীক্ষা দিতে পারবেন:",
    requestRetakeBtn: "এখনই পুনরায় কুইজ দিতে অ্যাডমিন অনুমোদনের অনুরোধ করুন",
    requestPending: "অ্যাডমিন অনুমোদনের অনুরোধ পেন্ডিং আছে ⏳",
    requestApproved: "অনুরোধ অনুমোদিত! আপনি এখন পুনরায় কুইজে অংশ নিতে পারেন 🔓",
    requestRejected: "অনুরোধ প্রত্যাখ্যান করা হয়েছে। আপনি আবার অনুরোধ পাঠাতে পারেন ❌",
    sendRequestSuccess: "পুনরায় অংশ নেওয়ার অনুরোধ অ্যাডমিন অনুমোদনের জন্য প্রেরণ করা হয়েছে!",
    approvalsTab: "রিটেক অনুমোদন",
    adminApprovalsTitle: "শিক্ষার্থীদের রিটেক অনুরোধসমূহ",
    approveBtn: "অনুমোদন করুন",
    rejectBtn: "প্রত্যাখ্যান করুন",
    studentLabel: "শিক্ষার্থী",
    requestedExam: "অনুরোধকৃত পরীক্ষা",
    requestDate: "অনুরোধের তারিখ",
    statusCol: "অবস্থা",
    actionsCol: "অ্যাকশন",
    noPendingRequests: "কোনো পেন্ডিং অথবা পূর্ববর্তী রিটেক অনুরোধ পাওয়া যায়নি।",

    // Dynamic Submenus
    subMenusTab: "উপ-মেনু",
    manageSubMenusTitle: "শ্রেণী ভিত্তিক উপ-মেনু ব্যবস্থাপনা (শ্রেণী ৬ থেকে ১০)",
    addSubMenuBtn: "উপ-মেনু যোগ করুন",
    subMenuParentLabel: "প্যারেন্ট শ্রেণী ক্যাটাগরি",
    subMenuTitleEn: "উপ-মেনু নাম (ইংরেজি)",
    subMenuTitleBn: "উপ-মেনু নাম (বাংলা)",
    existingSubMenusTitle: "বিদ্যমান উপ-মেনুসমূহ",
    deleteSubMenuTooltip: "উপ-মেনু মুছে ফেলুন",
    noSubMenusFound: "কোনো কাস্টম উপ-মেনু পাওয়া যায়নি।",
    linkedSubMenuLabel: "সংশ্লিষ্ট উপ-মেনু",
    selectSubMenuDefault: "উপ-মেনু নির্বাচন করুন (ঐচ্ছিক)",
    clearFilterBtn: "উপ-মেনু ফিল্টার মুছুন",
    activeSubMenuLabel: "সক্রিয় উপ-মেনু ফিল্টার:",
    confirmSignOutTitle: "আপনি কি নিশ্চিত যে লগ আউট করতে চান?",
    confirmSignOutDesc: "আপনি আপনার সেশন থেকে লগ আউট হয়ে যাবেন। কোনো চলমান পরীক্ষা ড্রাফট থেকে থাকলে তা বাতিল হবে।",
    confirmClearFiltersTitle: "আপনি কি নিশ্চিত যে ফিল্টার বাতিল করতে চান?",
    confirmClearFiltersDesc: "এটি আপনার সমস্ত সক্রিয় উপ-মেনু ও শ্রেণীভিত্তিক নির্বাচন বাতিল করে সব পরীক্ষা প্রদর্শন করবে।",
    confirmSubmitAnswersTitle: "আপনি কি নিশ্চিত যে উত্তরপত্র সাবমিট করতে চান?",
    confirmSubmitAnswersDesc: "আপনার উত্তরপত্র মূল্যায়নের জন্য জমা দেওয়া হবে। একবার জমা দেওয়ার পর আপনি আর উত্তর পরিবর্তন করতে পারবেন না।",

    // Offline capabilities
    offlineStatus: "অফলাইন মোড",
    onlineStatus: "অনলাইন মোড",
    viewCachedQuizzes: "ক্যাশড কুইজ দেখছেন",
    cachedBadge: "অফলাইনে প্রস্তুত",
    downloadForOffline: "অফলাইন ডাউনলোড",
    savedOfflineDetail: "ডিভাইসে সংরক্ষিত",
    offlineSyncPendingCount: "টি পরীক্ষা সিঙ্কের অপেক্ষায়",
    syncOfflineAttemptsNow: "সংরক্ষিত পরীক্ষা সিঙ্ক করুন",
    syncSuccess: "সফলভাবে ডাটা সিঙ্ক্রোনাইজড হয়েছে!",
    syncedLabel: "সিঙ্কড",
    offlineAttemptSavedAlert: "অফলাইন পরীক্ষা সম্পন্ন হয়েছে। আপনার স্কোর ডিভাইসে সংরক্ষিত হয়েছে এবং ইন্টারনেট সংযোগ ফিরলে তা স্বয়ংক্রিয়ভাবে সিঙ্ক হবে!",
    noInternetConnection: "কোনো ইন্টারনেট সংযোগ নেই।",
    showingLocalCache: "ক্যাশে সংরক্ষিত অফলাইন কুইজ দেখানো হচ্ছে।",

    // Guest Invite translations
    guestHeaderTitle: "অতিথি শিক্ষার্থী পোর্টাল",
    guestHeaderDesc: "সম্পূর্ণ অ্যাকাউন্ট নিবন্ধনহীনভাবে পরীক্ষায় অংশগ্রহণের জন্য আপনাকে আমন্ত্রণ জানানো হয়েছে। শুরু করতে নিচে আপনার নাম লিখুন।",
    guestInputName: "শুরু করতে আপনার পুরো নাম লিখুন",
    guestInputNamePlaceholder: "যেমন: রহিম উদ্দিন",
    startAsGuestBtn: "অংশগ্রহণ ও পরীক্ষা শুরু করুন ➔",
    orLoginRegister: "মূল লগইন / রেজিস্ট্রেশন পেজে ফিরে যান",
    inviteLinkBtn: "আমন্ত্রণ লিংক কপি করুন",
    inviteCopiedToast: "আমন্ত্রণ লিংক ক্লিপবোর্ডে কপি করা হয়েছে!"
  }
};
